# Generated by Django 5.0.7 on 2024-11-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_top', models.CharField(max_length=30)),
                ('text_big', models.CharField(max_length=50)),
                ('text_end', models.TextField()),
                ('but_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=15)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeaderTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('icon', models.CharField(max_length=5)),
                ('adress', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MainFourLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('numbertwo', models.CharField(max_length=30)),
                ('nametwo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainFourRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MainFourTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainOneLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('but_name', models.CharField(max_length=40)),
                ('but_adress', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MainOneRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.IntegerField()),
                ('img', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainOneTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69)),
            ],
        ),
        migrations.CreateModel(
            name='MainTheeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('pay', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MainTheeTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainTwoLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('but_name', models.CharField(max_length=40)),
                ('but_adress', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MainTwoRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
